// Sample product dataset for demonstration of filtering, sorting, and pagination
// In a real app, fetch this from backend APIs.

export const SAMPLE_PRODUCTS = [
  // --- Indoor Plants (Air-Purifying) ---
  {
    id: 'ip1',
    name: 'Snake Plant (Sansevieria trifasciata)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 399,
    originalPrice: 499,
    discount: 20,
    inStock: true,
    image: '/snake plant.avif',
    description: 'Air-purifying, low-light tolerant. Botanical: Sansevieria trifasciata.',
    rating: 4,
    reviews: 124,
    popularity: 120,
    isNew: false,
    tags: ['Air-Purifying', 'Low-Maintenance']
  },
  {
    id: 'ip2',
    name: 'Spider Plant (Chlorophytum comosum)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 299,
    inStock: true,
    image: '',
    description: 'Excellent air purifier; easy to grow. Botanical: Chlorophytum comosum.',
    rating: 5,
    reviews: 88,
    popularity: 100,
    isNew: true,
    tags: ['Air-Purifying', 'Low-Maintenance']
  },
  {
    id: 'ip3',
    name: 'Areca Palm (Dypsis lutescens)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 549,
    inStock: true,
    image: '',
    description: 'Popular indoor palm; humid-loving. Botanical: Dypsis lutescens.',
    rating: 5,
    reviews: 210,
    popularity: 150,
    isNew: false,
    tags: ['Air-Purifying']
  },
  {
    id: 'ip4',
    name: 'Peace Lily (Spathiphyllum wallisii)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 449,
    inStock: true,
    image: '',
    description: 'Elegant flowers; tolerates low light. Botanical: Spathiphyllum wallisii.',
    rating: 4,
    reviews: 160,
    popularity: 130,
    isNew: false,
    tags: ['Air-Purifying', 'Flowering']
  },
  {
    id: 'ip5',
    name: 'Rubber Plant (Ficus elastica)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 599,
    inStock: true,
    image: '',
    description: 'Glossy leaves; statement indoor plant. Botanical: Ficus elastica.',
    rating: 4,
    reviews: 75,
    popularity: 90,
    isNew: false,
    tags: ['Air-Purifying']
  },

  // --- Indoor Plants (Low-Maintenance) ---
  {
    id: 'ip6',
    name: 'ZZ Plant (Zamioculcas zamiifolia)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 549,
    inStock: true,
    image: '',
    description: 'Thrives on neglect; drought tolerant. Botanical: Zamioculcas zamiifolia.',
    rating: 5,
    reviews: 92,
    popularity: 140,
    isNew: false,
    tags: ['Low-Maintenance']
  },
  {
    id: 'ip7',
    name: 'Pothos / Money Plant (Epipremnum aureum)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 249,
    inStock: true,
    image: '',
    description: 'Beginner-friendly trailing plant. Botanical: Epipremnum aureum.',
    rating: 5,
    reviews: 320,
    popularity: 300,
    isNew: false,
    tags: ['Low-Maintenance', 'Air-Purifying']
  },
  {
    id: 'ip8',
    name: 'Chinese Evergreen (Aglaonema)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 399,
    inStock: true,
    image: '',
    description: 'Colorful foliage; low-light tolerant. Botanical: Aglaonema.',
    rating: 4,
    reviews: 60,
    popularity: 110,
    isNew: false,
    tags: ['Low-Maintenance']
  },
  {
    id: 'ip9',
    name: 'Jade Plant (Crassula ovata)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 299,
    inStock: true,
    image: '',
    description: 'Succulent with thick leaves. Botanical: Crassula ovata.',
    rating: 4,
    reviews: 58,
    popularity: 100,
    isNew: false,
    tags: ['Low-Maintenance', 'Succulent']
  },
  {
    id: 'ip10',
    name: 'Lucky Bamboo (Dracaena sanderiana)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 349,
    inStock: true,
    image: '',
    description: 'Popular tabletop plant; easy care. Botanical: Dracaena sanderiana.',
    rating: 4,
    reviews: 70,
    popularity: 105,
    isNew: true,
    tags: ['Low-Maintenance']
  },

  // --- Indoor Plants (Flowering) ---
  {
    id: 'ip11',
    name: 'Anthurium (Anthurium andraeanum)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 599,
    inStock: true,
    image: '',
    description: 'Striking red spathes; indoor flowering plant.',
    rating: 5,
    reviews: 80,
    popularity: 125,
    isNew: false,
    tags: ['Flowering']
  },
  {
    id: 'ip12',
    name: 'African Violet (Saintpaulia)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 299,
    inStock: true,
    image: '',
    description: 'Compact flowering plant; bright indirect light.',
    rating: 4,
    reviews: 45,
    popularity: 70,
    isNew: false,
    tags: ['Flowering']
  },
  {
    id: 'ip13',
    name: 'Orchid (Phalaenopsis)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 599,
    inStock: true,
    image: '',
    description: 'Elegant long-lasting blooms; indoor favorite.',
    rating: 5,
    reviews: 115,
    popularity: 150,
    isNew: false,
    tags: ['Flowering']
  },
  {
    id: 'ip14',
    name: 'Kalanchoe (Kalanchoe blossfeldiana)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 249,
    inStock: true,
    image: '',
    description: 'Bright, colorful blooms; drought tolerant.',
    rating: 4,
    reviews: 40,
    popularity: 60,
    isNew: false,
    tags: ['Flowering']
  },
  {
    id: 'ip15',
    name: 'Gerbera Daisy (Gerbera jamesonii)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 349,
    inStock: true,
    image: '',
    description: 'Cheerful daisy blooms indoors.',
    rating: 4,
    reviews: 55,
    popularity: 75,
    isNew: false,
    tags: ['Flowering']
  },

  // --- Succulents & Mini Cactus ---
  {
    id: 'ip16',
    name: 'Aloe Vera (Aloe barbadensis miller)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 249,
    inStock: true,
    image: '',
    description: 'Medicinal succulent; easy care.',
    rating: 4,
    reviews: 85,
    popularity: 100,
    isNew: false,
    tags: ['Succulent']
  },
  {
    id: 'ip17',
    name: 'Haworthia (Haworthia attenuata)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 249,
    inStock: true,
    image: '',
    description: 'Compact rosette succulent; zebra stripes.',
    rating: 4,
    reviews: 35,
    popularity: 50,
    isNew: false,
    tags: ['Succulent']
  },
  {
    id: 'ip18',
    name: 'Echeveria (Echeveria elegans)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 299,
    inStock: true,
    image: '',
    description: 'Rosette succulent; pastel tones.',
    rating: 4,
    reviews: 28,
    popularity: 48,
    isNew: false,
    tags: ['Succulent']
  },
  {
    id: 'ip19',
    name: 'Mini Cactus Varieties',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 200,
    inStock: true,
    image: '',
    description: 'Assorted mini cacti; perfect for tabletops.',
    rating: 4,
    reviews: 33,
    popularity: 55,
    isNew: false,
    tags: ['Succulent']
  },
  {
    id: 'ip20',
    name: 'Sedum (Sedum morganianum – Burro’s Tail)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 299,
    inStock: true,
    image: '',
    description: 'Trailing succulent with bead-like leaves.',
    rating: 4,
    reviews: 22,
    popularity: 42,
    isNew: false,
    tags: ['Succulent']
  },
  // Plants
  {
    id: 'p1',
    name: 'Snake Plant',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 15.99,
    originalPrice: 19.99,
    discount: 20,
    inStock: true,
    image:
      '/snake plant.avif',
    description: 'Low maintenance indoor air-purifying plant.',
    rating: 4,
    reviews: 124,
    popularity: 90,
    isNew: false,
  },
  {
    id: 'p2',
    name: 'Areca Palm',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 24.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=600&q=80',
    description: 'Elegant indoor palm, improves air quality.',
    rating: 5,
    reviews: 210,
    popularity: 120,
    isNew: true,
  },
  {
    id: 'p3',
    name: 'Bougainvillea',
    category: 'Plants',
    subcategory: 'Outdoor',
    price: 9.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1466840861458-a36c1ccdb97e?auto=format&fit=crop&w=600&q=80',
    description: 'Vibrant flowering outdoor plant.',
    rating: 4,
    reviews: 56,
    popularity: 75,
    isNew: false,
  },
  {
    id: 'p4',
    name: 'Tulsi (Holy Basil)',
    category: 'Plants',
    subcategory: 'Medicinal/Herbal',
    price: 4.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1524594074413-5a753e8e56a8?auto=format&fit=crop&w=600&q=80',
    description: 'Sacred medicinal plant with many health benefits.',
    rating: 5,
    reviews: 310,
    popularity: 200,
    isNew: false,
  },
  {
    id: 'p5',
    name: 'Mango Sapling',
    category: 'Plants',
    subcategory: 'Fruit',
    price: 12.99,
    inStock: false,
    image:
      'https://images.unsplash.com/photo-1553456558-aff63285bdd5?auto=format&fit=crop&w=600&q=80',
    description: 'Young mango plant for home garden.',
    rating: 4,
    reviews: 48,
    popularity: 60,
    isNew: false,
  },
  {
    id: 'p6',
    name: 'Peace Lily',
    category: 'Plants',
    subcategory: 'Air-Purifying',
    price: 14.49,
    originalPrice: 18.49,
    discount: 22,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1524593950739-4702d45e3673?auto=format&fit=crop&w=600&q=80',
    description: 'Beautiful indoor plant with white blooms.',
    rating: 4,
    reviews: 160,
    popularity: 110,
    isNew: false,
  },

  // Crops & Seeds
  {
    id: 'c1',
    name: 'Tomato Seeds (Heirloom)',
    category: 'Crops & Seeds',
    subcategory: 'Vegetables',
    price: 2.49,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&w=600&q=80',
    description: 'High-yield heirloom tomato seeds.',
    rating: 4,
    reviews: 95,
    popularity: 85,
    isNew: true,
  },
  {
    id: 'c2',
    name: 'Basil Seeds',
    category: 'Crops & Seeds',
    subcategory: 'Spices/Herbs',
    price: 1.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1501004318963-d4f9f3f8f3a9?auto=format&fit=crop&w=600&q=80',
    description: 'Aromatic herb seeds for kitchen garden.',
    rating: 5,
    reviews: 40,
    popularity: 50,
    isNew: false,
  },
  {
    id: 'c3',
    name: 'Wheat Grain Seeds',
    category: 'Crops & Seeds',
    subcategory: 'Grains/Pulses',
    price: 3.99,
    inStock: false,
    image:
      'https://images.unsplash.com/photo-1440174106086-79de1599b3fa?auto=format&fit=crop&w=600&q=80',
    description: 'Quality wheat seeds for sowing.',
    rating: 3,
    reviews: 20,
    popularity: 30,
    isNew: false,
  },

  // Pots & Planters
  {
    id: 'pp1',
    name: 'Ceramic Planter - White',
    category: 'Pots & Planters',
    subcategory: 'Ceramic',
    price: 9.49,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=600&q=80',
    description: 'Minimal ceramic pot for indoor plants.',
    rating: 4,
    reviews: 66,
    popularity: 70,
    isNew: true,
  },
  {
    id: 'pp2',
    name: 'Terracotta Pot - Medium',
    category: 'Pots & Planters',
    subcategory: 'Clay/Terracotta',
    price: 6.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1504194104404-433180773017?auto=format&fit=crop&w=600&q=80',
    description: 'Classic breathable terracotta planter.',
    rating: 5,
    reviews: 150,
    popularity: 160,
    isNew: false,
  },
  {
    id: 'pp3',
    name: 'Hanging Planter - Jute',
    category: 'Pots & Planters',
    subcategory: 'Hanging',
    price: 8.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1522184216315-dc2a41a11622?auto=format&fit=crop&w=600&q=80',
    description: 'Eco-friendly jute hanging planter.',
    rating: 4,
    reviews: 32,
    popularity: 40,
    isNew: false,
  },

  // Soil & Fertilizers
  {
    id: 'sf1',
    name: 'Organic Potting Mix 5kg',
    category: 'Soil & Fertilizers',
    subcategory: 'Potting Mix',
    price: 7.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1586205237529-0312a66c1f40?auto=format&fit=crop&w=600&q=80',
    description: 'Nutrient-rich potting mix for healthy growth.',
    rating: 4,
    reviews: 77,
    popularity: 95,
    isNew: false,
  },
  {
    id: 'sf2',
    name: 'Vermicompost 5kg',
    category: 'Soil & Fertilizers',
    subcategory: 'Compost/Manure',
    price: 6.49,
    inStock: false,
    image:
      'https://images.unsplash.com/photo-1586985564150-3a7d0a87df12?auto=format&fit=crop&w=600&q=80',
    description: 'Organic compost for improved soil structure.',
    rating: 4,
    reviews: 52,
    popularity: 65,
    isNew: false,
  },

  // Gardening Tools
  {
    id: 'gt1',
    name: 'Hand Trowel',
    category: 'Gardening Tools',
    subcategory: 'Hand Tools',
    price: 4.49,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1469536526925-9b5547cd1c9a?auto=format&fit=crop&w=600&q=80',
    description: 'Durable stainless steel hand trowel.',
    rating: 4,
    reviews: 110,
    popularity: 130,
    isNew: false,
  },
  {
    id: 'gt2',
    name: 'Watering Can 5L',
    category: 'Gardening Tools',
    subcategory: 'Watering Tools',
    price: 12.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1472141528297-94f5f02b8e32?auto=format&fit=crop&w=600&q=80',
    description: 'Lightweight watering can for gardens.',
    rating: 5,
    reviews: 95,
    popularity: 140,
    isNew: true,
  },

  // Herbal & Eco Products
  {
    id: 'he1',
    name: 'Aloe Vera Gel (Organic)',
    category: 'Herbal & Eco Products',
    subcategory: 'Herbal Remedies',
    price: 5.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1604336755604-56c10b0226c5?auto=format&fit=crop&w=600&q=80',
    description: 'Pure organic aloe vera gel for skin and hair.',
    rating: 4,
    reviews: 85,
    popularity: 100,
    isNew: false,
  },
  {
    id: 'he2',
    name: 'Eco-Friendly Seed Starter Kit',
    category: 'Herbal & Eco Products',
    subcategory: 'Eco-Friendly Packs',
    price: 14.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1524594227083-80b900d0e83a?auto=format&fit=crop&w=600&q=80',
    description: 'Sustainable seed starter kit with biodegradable pots.',
    rating: 5,
    reviews: 65,
    popularity: 115,
    isNew: true,
  },

  // More to reach > 20 for pagination demo
  {
    id: 'p7',
    name: 'Rose (Red)',
    category: 'Plants',
    subcategory: 'Flowering',
    price: 7.49,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&w=600&q=80',
    description: 'Classic red rose plant.',
    rating: 4,
    reviews: 200,
    popularity: 180,
    isNew: false,
  },
  {
    id: 'p8',
    name: 'Money Plant (Pothos)',
    category: 'Plants',
    subcategory: 'Indoor',
    price: 5.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1531642769090-acef73e3f18c?auto=format&fit=crop&w=600&q=80',
    description: 'Easy indoor plant, great for beginners.',
    rating: 5,
    reviews: 320,
    popularity: 300,
    isNew: false,
  },
  {
    id: 'gt3',
    name: 'Garden Support Stakes (Pack of 10)',
    category: 'Gardening Tools',
    subcategory: 'Supports',
    price: 9.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1623330189643-3b2c65cf6ccc?auto=format&fit=crop&w=600&q=80',
    description: 'Durable plant support stakes for garden.',
    rating: 3,
    reviews: 22,
    popularity: 25,
    isNew: false,
  },
  {
    id: 'pp4',
    name: 'Self-Watering Planter',
    category: 'Pots & Planters',
    subcategory: 'Self-Watering',
    price: 16.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1528660493886-d58f1a3e9e51?auto=format&fit=crop&w=600&q=80',
    description: 'Modern self-watering pot for busy plant parents.',
    rating: 4,
    reviews: 45,
    popularity: 70,
    isNew: true,
  },
  {
    id: 'sf3',
    name: 'NPK Chemical Fertilizer 1kg',
    category: 'Soil & Fertilizers',
    subcategory: 'Chemical Fertilizers',
    price: 4.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
    description: 'Balanced NPK fertilizer for quick growth.',
    rating: 4,
    reviews: 41,
    popularity: 66,
    isNew: false,
  },
  {
    id: 'sf4',
    name: 'Soil Conditioner 2kg',
    category: 'Soil & Fertilizers',
    subcategory: 'Soil Conditioners',
    price: 5.99,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?auto=format&fit=crop&w=600&q=80',
    description: 'Improves soil aeration and structure.',
    rating: 3,
    reviews: 10,
    popularity: 15,
    isNew: false,
  },
  {
    id: 'c4',
    name: 'Strawberry Seeds',
    category: 'Crops & Seeds',
    subcategory: 'Fruits',
    price: 3.49,
    inStock: true,
    image:
      'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    description: 'Grow sweet strawberries at home.',
    rating: 4,
    reviews: 58,
    popularity: 80,
    isNew: true,
  },
  {
    id: 'pp5',
    name: 'Decorative Planter - Patterned',
    category: 'Pots & Planters',
    subcategory: 'Decorative',
    price: 11.99,
    inStock: false,
    image:
      'https://images.unsplash.com/photo-1600359755835-15800fdd2bc8?auto=format&fit=crop&w=600&q=80',
    description: 'Stylish patterned pot for home decor.',
    rating: 5,
    reviews: 70,
    popularity: 95,
    isNew: false,
  },
];